name: ie-bank-frontend

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:

  FRONTEND_WEBAPP_DEV: sbrenner-fe-dev
  FRONTEND_WEBAPP_UAT: sbrenner-fe-uat


jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: npm install, build, and test (Development)
        run: |
          npm install

          npm run build:dev 
      - name: Upload artifact for deployment job (Development)

        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist/  # Specify the correct output path

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-dev
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:

      - name: Download artifact from build-dev job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev
          path: ./build  # Download to a specific directory

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure Web App - Development'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: ./build  # Point to the correct directory

  build-uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: npm install, build, and test (UAT)
        run: |
          npm install
          npm run build:uat ## Ensure this builds to ⁠ dist/ ⁠
      - name: Upload artifact for deployment job (UAT)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist/  # Specify the correct output path
#try
  deploy-uat:
    runs-on: ubuntu-latest
    needs: [build-uat, deploy-dev]
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build-uat job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat
          path: ./build  # Download to a specific directory
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure Web App - UAT'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: ./build  # Point to the correct directory